spring.application.name=login-system

spring.datasource.url=jdbc:postgresql://localhost:5432/login_system
spring.datasource.username=postgres
spring.datasource.password=T0039270cab!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect